
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMILLAS = 93;
  public static final int IDENTIFICADOR = 95;
  public static final int PIXELS = 84;
  public static final int H1 = 16;
  public static final int COMP_MAYOR = 48;
  public static final int TYPE = 24;
  public static final int HEX = 82;
  public static final int MODO = 41;
  public static final int ROWS = 28;
  public static final int ASC = 56;
  public static final int NAME = 26;
  public static final int CORCHETEC = 40;
  public static final int INIT = 72;
  public static final int CORCHETEA = 39;
  public static final int ALT = 33;
  public static final int FNUM = 62;
  public static final int ONLOAD = 96;
  public static final int COMP_DIF = 46;
  public static final int POR = 54;
  public static final int NUMERO = 83;
  public static final int FINETIQUETA = 42;
  public static final int NOT = 51;
  public static final int TIPOS = 89;
  public static final int THEN = 80;
  public static final int FPAR = 58;
  public static final int WIDTH = 31;
  public static final int REVERSE = 60;
  public static final int COMP_IGUAL = 45;
  public static final int DOSP = 73;
  public static final int CLASS = 29;
  public static final int SELECT = 10;
  public static final int TEXTAREA = 9;
  public static final int HUNTIL = 77;
  public static final int TXTA = 23;
  public static final int IGUAL = 92;
  public static final int CLASE = 90;
  public static final int FUENTES = 87;
  public static final int WHILE = 78;
  public static final int COLS = 27;
  public static final int GET_ELEMENT = 70;
  public static final int ONC = 34;
  public static final int COMP_MENOR = 47;
  public static final int ALIGN = 88;
  public static final int DECIMAL = 68;
  public static final int FCARACTER = 61;
  public static final int CHAR = 69;
  public static final int BOOLEAN = 66;
  public static final int ERRORLEX = 97;
  public static final int INPUT = 8;
  public static final int GCIC = 2;
  public static final int DIV = 12;
  public static final int P = 17;
  public static final int ELSE = 75;
  public static final int MENOS = 53;
  public static final int MAS = 52;
  public static final int INT = 65;
  public static final int URL = 91;
  public static final int LINK = 5;
  public static final int EOF = 0;
  public static final int PUNTOC = 71;
  public static final int BUTTON = 15;
  public static final int REPEAT = 76;
  public static final int SPAM = 7;
  public static final int SCRIPT = 94;
  public static final int ENTRE = 55;
  public static final int SRC = 30;
  public static final int FTS = 21;
  public static final int BODY = 6;
  public static final int HREF = 18;
  public static final int TITLE = 4;
  public static final int OR = 49;
  public static final int error = 1;
  public static final int EXIT = 64;
  public static final int FIMPAR = 59;
  public static final int THENW = 79;
  public static final int IF = 74;
  public static final int DESC = 57;
  public static final int ID = 25;
  public static final int FTF = 22;
  public static final int COLOR = 20;
  public static final int MENORQ = 44;
  public static final int HEAD = 3;
  public static final int ALERT = 63;
  public static final int IMG = 13;
  public static final int MAYORQ = 43;
  public static final int PARENTESISC = 36;
  public static final int PARENTESISA = 35;
  public static final int HEIGHT = 32;
  public static final int BR = 14;
  public static final int OPTION = 11;
  public static final int INSERT = 81;
  public static final int STRING = 67;
  public static final int BG = 19;
  public static final int AND = 50;
  public static final int COLORES = 86;
  public static final int LLAVEC = 38;
  public static final int PORC = 85;
  public static final int LLAVEA = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GCIC",
  "HEAD",
  "TITLE",
  "LINK",
  "BODY",
  "SPAM",
  "INPUT",
  "TEXTAREA",
  "SELECT",
  "OPTION",
  "DIV",
  "IMG",
  "BR",
  "BUTTON",
  "H1",
  "P",
  "HREF",
  "BG",
  "COLOR",
  "FTS",
  "FTF",
  "TXTA",
  "TYPE",
  "ID",
  "NAME",
  "COLS",
  "ROWS",
  "CLASS",
  "SRC",
  "WIDTH",
  "HEIGHT",
  "ALT",
  "ONC",
  "PARENTESISA",
  "PARENTESISC",
  "LLAVEA",
  "LLAVEC",
  "CORCHETEA",
  "CORCHETEC",
  "MODO",
  "FINETIQUETA",
  "MAYORQ",
  "MENORQ",
  "COMP_IGUAL",
  "COMP_DIF",
  "COMP_MENOR",
  "COMP_MAYOR",
  "OR",
  "AND",
  "NOT",
  "MAS",
  "MENOS",
  "POR",
  "ENTRE",
  "ASC",
  "DESC",
  "FPAR",
  "FIMPAR",
  "REVERSE",
  "FCARACTER",
  "FNUM",
  "ALERT",
  "EXIT",
  "INT",
  "BOOLEAN",
  "STRING",
  "DECIMAL",
  "CHAR",
  "GET_ELEMENT",
  "PUNTOC",
  "INIT",
  "DOSP",
  "IF",
  "ELSE",
  "REPEAT",
  "HUNTIL",
  "WHILE",
  "THENW",
  "THEN",
  "INSERT",
  "HEX",
  "NUMERO",
  "PIXELS",
  "PORC",
  "COLORES",
  "FUENTES",
  "ALIGN",
  "TIPOS",
  "CLASE",
  "URL",
  "IGUAL",
  "COMILLAS",
  "SCRIPT",
  "IDENTIFICADOR",
  "ONLOAD",
  "ERRORLEX"
  };
}

