
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class symDB {
  /* terminals */
  public static final int CAPTCHA = 4;
  public static final int INVERTIDA = 15;
  public static final int VECES = 6;
  public static final int CORCHETEC = 14;
  public static final int IGUAL = 7;
  public static final int CORCHETEA = 13;
  public static final int URL = 18;
  public static final int LLAVEC = 12;
  public static final int LLAVEA = 11;
  public static final int STRING = 17;
  public static final int COMA = 3;
  public static final int FALLOS = 9;
  public static final int NOMBRE = 5;
  public static final int EOF = 0;
  public static final int BASE = 2;
  public static final int FECHA = 10;
  public static final int error = 1;
  public static final int ACIERTOS = 8;
  public static final int TITULO = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BASE",
  "COMA",
  "CAPTCHA",
  "NOMBRE",
  "VECES",
  "IGUAL",
  "ACIERTOS",
  "FALLOS",
  "FECHA",
  "LLAVEA",
  "LLAVEC",
  "CORCHETEA",
  "CORCHETEC",
  "INVERTIDA",
  "TITULO",
  "STRING",
  "URL"
  };
}

